spring:
  application:
    name: bank-cards
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
    disable-swagger-default-url: true

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    ttl: ${APP_JWT_TTL}
  card:
    encryption-key: ${APP_CARD_ENCRYPTION_KEY}
    fingerprint-key: ${APP_CARD_FINGERPRINT_KEY}
  admin:
    username: ${APP_ADMIN_USERNAME}
    password: ${APP_ADMIN_PASSWORD}
